const x = DOCENCIA: {
  "ACTIVIDAD_DOCENTE": 
      {},
  "PRE_GRADO": 
      {},
  "POST_GRADO": [
      {"FECHA": "2004-09-01",
      "DESCRIPCION": " CONFERENCIA " NUEVOS ANTIFÚNGICOS ", SEGUNDO COLOQUIO INFECTOLÓGICO DEL SUR, FACULTAD DE MEDICINA, UNIVERSIDAD DE CONCEPCION."
  },				{"FECHA": "2004-00-01",
      "DESCRIPCION": " EXPOSITOR EN EL VI CURSO DE PROBLEMAS FRECUENTES EN ATENCIÓN PRIMARIA 2004, " VACUNACIONES EN LOS ADULTOS ", SOCIEDAD DE MEDICINA INTERNA, FILIAL CONCEPCION"
  },				{"FECHA": "2006-03-01",
      "DESCRIPCION": " DOCENTE DEPTO. DE MEDICINA, UNIVERSIDAD DE CONCEPCION"
  },				{"FECHA": "2003-08-01",
      "DESCRIPCION": " CONFERENCIA " EXPERIENCIA Y MANEJO DE LAS TOXICIDADES EN ESQUEMAS CON NRTI ALTERNATIVOS " VI CURSO DE TERAPIA ANTIRETROVIRAL, SOCIEDAD CHILENA DE INFECTOLOGÍA."
  },				{"FECHA": "2004-04-01",
      "DESCRIPCION": " EXPOSITOR EN EL SEGUNDO CURSO GASTROENTEROLOGÍA, HEMATOLOGÍA E INFECTOLOGÍA DE LA FACULTAD DE MEDICINA UNIVERSIDAD DE CONCEPCION, " INFECCIONES ENTÉRICAS ". CONCEPCIÓN"
  },				{"FECHA": "2004-08-01",
      "DESCRIPCION": " CONFERENCIA " INFECCIÓN URINARIA EN EL ADULTO ". XIV CURSO DE TERAPIA ANTIMICROBIANA, SOCIEDAD CHILENA DE INFECTOLOGÍA, SANTIAGO"
  },				{"FECHA": "2004-10-01",
      "DESCRIPCION": " CONFERENCIA " PROFILAXIS DE INFECCIONES OPORTUNISTAS Y TERAPOA DE MANTENCIÓN DURANTE LA TERAPOA ANTIRETROVIRAL EXITOSA ". XXI CONGRESO CHILENO DE INFECTOLOGÍA, VIÑA DEL MAR."
  },				{"FECHA": "2005-08-01",
      "DESCRIPCION": " CONFERENCIA " PRINCIPALES CUADROS DE RECONSTITUCIÓN INMUNE EN PACIENTES CON VIH ", VIII CURSO DE TERAPIA ANTIRETROVIRAL, SOCIEDAD DE INFECTOLOGÍA."
  }]
}